trigger:
  branches:
    include:
    - features/*
    - bug/*
    - master
    - staging

resources:
  containers:
  - container: mariadb
    image: "mariadb:10.2"
    ports:
    - 3306
    env:
    - MYSQL_ROOT_PASSWORD: secret
    - MYSQL_DATABASE: test
  - container: redis
    image: "redis:5"
    ports:
    - 6379

variables:
  azureSubscriptionEndpoint: vaop-arm
  azureContainerRegistry: vaopcr.azurecr.io
  phpVersion: 7.2

jobs:

- job: 'PHP'
  pool:
    vmImage: 'Ubuntu-16.04'
  services:
    mariadb: mariadb
    redis: redis

  steps:
  - script: "export DB_PORT=${AGENT_SERVICES_MARIADB_PORTS_3306}"
    displayName: 'export DB_PORT'
  - script: "export REDIS_PORT=${AGENT_SERVICES_REDIS_PORTS_6379}"
    displayName: 'export REDIS_PORT'

  - script: |
      sudo update-alternatives --set php /usr/bin/php$(phpVersion)
      sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
      sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
      sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
      sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
      php -version
    displayName: 'Use PHP version $(phpVersion)'

  - script: composer config http-basic.nova.laravel.com $(NOVA_USERNAME) $(NOVA_PASSWORD)
    displayName: 'composer nova authentication'

  - script: composer install --no-interaction --prefer-dist
    displayName: 'composer install'

  - script: cp .env.testing .env
    displayName: 'setup .env'

  - script: php artisan key:generate
    displayName: 'generate encryption key'

  - script: php artisan migrate --seed
    displayName: 'database migrations and seeding'

  - script: ./vendor/bin/phpunit
    displayName: 'phpunit testing'

- job: 'NodeJS'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'npm install'

  - script: npm run prod
    displayName: 'npm install prod build'

- job: 'Dockerfile'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: Docker@1
    displayName: Container registry login
    inputs:
      command: login
      azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureContainerRegistry: $(azureContainerRegistry)
  - task: Docker@1
    displayName: Build image
    inputs:
      command: build
      azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureContainerRegistry: $(azureContainerRegistry)
      dockerFile: Dockerfile
      imageName: $(Build.Repository.Name)
  - task: Docker@1
    displayName: Tag image
    inputs:
      command: tag
      azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureContainerRegistry: $(azureContainerRegistry)
      imageName: $(azureContainerRegistry)/$(Build.Repository.Name):latest
      arguments: $(azureContainerRegistry)/$(Build.Repository.Name):$(Build.BuildNumber)
  - task: Docker@1
    displayName: Push image
    inputs:
      command: push
      azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
      azureContainerRegistry: $(azureContainerRegistry)
      imageName: $(Build.Repository.Name):$(Build.BuildNumber)
