apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vaop
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: vaop
    spec:
      containers:
        - name: laravel
          image: vaopcr.azurecr.io/atgi/vaop:20190611.1
          ports:
            - containerPort: 9000
              protocol: TCP
        - name: nginx
          image: nginx/nginx:alpine
          ports:
            - containerPort: 80
              protocol: TCP
        - name: redis
          image: redis/nginx:5.0.5
          ports:
            - containerPort: 6379
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vaop-ingress
  labels:
    app: vaop-ingress
spec:
  selector:
    app: vaop
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer
